//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.NationalityService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NationalityDto", Namespace="http://schemas.datacontract.org/2004/07/ApplicationServices.DTOs")]
    [System.SerializableAttribute()]
    public partial class NationalityDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NationalityService.INationality")]
    public interface INationality {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationality/Testing", ReplyAction="http://tempuri.org/INationality/TestingResponse")]
        string Testing();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationality/Testing", ReplyAction="http://tempuri.org/INationality/TestingResponse")]
        System.Threading.Tasks.Task<string> TestingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationality/GetNationalities", ReplyAction="http://tempuri.org/INationality/GetNationalitiesResponse")]
        WebSite.NationalityService.NationalityDto[] GetNationalities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationality/GetNationalities", ReplyAction="http://tempuri.org/INationality/GetNationalitiesResponse")]
        System.Threading.Tasks.Task<WebSite.NationalityService.NationalityDto[]> GetNationalitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationality/GetNationalityByID", ReplyAction="http://tempuri.org/INationality/GetNationalityByIDResponse")]
        WebSite.NationalityService.NationalityDto GetNationalityByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationality/GetNationalityByID", ReplyAction="http://tempuri.org/INationality/GetNationalityByIDResponse")]
        System.Threading.Tasks.Task<WebSite.NationalityService.NationalityDto> GetNationalityByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationality/PostNationality", ReplyAction="http://tempuri.org/INationality/PostNationalityResponse")]
        string PostNationality(WebSite.NationalityService.NationalityDto nationalityDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationality/PostNationality", ReplyAction="http://tempuri.org/INationality/PostNationalityResponse")]
        System.Threading.Tasks.Task<string> PostNationalityAsync(WebSite.NationalityService.NationalityDto nationalityDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationality/PutNationality", ReplyAction="http://tempuri.org/INationality/PutNationalityResponse")]
        string PutNationality(WebSite.NationalityService.NationalityDto nationalityDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationality/PutNationality", ReplyAction="http://tempuri.org/INationality/PutNationalityResponse")]
        System.Threading.Tasks.Task<string> PutNationalityAsync(WebSite.NationalityService.NationalityDto nationalityDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationality/DeleteNationality", ReplyAction="http://tempuri.org/INationality/DeleteNationalityResponse")]
        string DeleteNationality(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationality/DeleteNationality", ReplyAction="http://tempuri.org/INationality/DeleteNationalityResponse")]
        System.Threading.Tasks.Task<string> DeleteNationalityAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INationalityChannel : WebSite.NationalityService.INationality, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NationalityClient : System.ServiceModel.ClientBase<WebSite.NationalityService.INationality>, WebSite.NationalityService.INationality {
        
        public NationalityClient() {
        }
        
        public NationalityClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NationalityClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NationalityClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NationalityClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Testing() {
            return base.Channel.Testing();
        }
        
        public System.Threading.Tasks.Task<string> TestingAsync() {
            return base.Channel.TestingAsync();
        }
        
        public WebSite.NationalityService.NationalityDto[] GetNationalities() {
            return base.Channel.GetNationalities();
        }
        
        public System.Threading.Tasks.Task<WebSite.NationalityService.NationalityDto[]> GetNationalitiesAsync() {
            return base.Channel.GetNationalitiesAsync();
        }
        
        public WebSite.NationalityService.NationalityDto GetNationalityByID(int id) {
            return base.Channel.GetNationalityByID(id);
        }
        
        public System.Threading.Tasks.Task<WebSite.NationalityService.NationalityDto> GetNationalityByIDAsync(int id) {
            return base.Channel.GetNationalityByIDAsync(id);
        }
        
        public string PostNationality(WebSite.NationalityService.NationalityDto nationalityDto) {
            return base.Channel.PostNationality(nationalityDto);
        }
        
        public System.Threading.Tasks.Task<string> PostNationalityAsync(WebSite.NationalityService.NationalityDto nationalityDto) {
            return base.Channel.PostNationalityAsync(nationalityDto);
        }
        
        public string PutNationality(WebSite.NationalityService.NationalityDto nationalityDto) {
            return base.Channel.PutNationality(nationalityDto);
        }
        
        public System.Threading.Tasks.Task<string> PutNationalityAsync(WebSite.NationalityService.NationalityDto nationalityDto) {
            return base.Channel.PutNationalityAsync(nationalityDto);
        }
        
        public string DeleteNationality(int id) {
            return base.Channel.DeleteNationality(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteNationalityAsync(int id) {
            return base.Channel.DeleteNationalityAsync(id);
        }
    }
}
